// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using muzickeStolice.Data;

#nullable disable

namespace muzickeStolice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240702170910_ChangedInterface")]
    partial class ChangedInterface
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("muzickeStolice.Model.Bend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DatumOsnivanja")
                        .HasColumnType("date");

                    b.Property<int>("IzvodjacID")
                        .HasColumnType("integer");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IzvodjacID");

                    b.ToTable("Bendovi");
                });

            modelBuilder.Entity("muzickeStolice.Model.Izvodjac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("MuzickoDeloId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("MuzickoDeloId");

                    b.ToTable("Izvodjac");
                });

            modelBuilder.Entity("muzickeStolice.Model.MuzickoDelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OcenljivoID")
                        .HasColumnType("integer");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<string>("ZanrDelaNaziv")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OcenljivoID");

                    b.HasIndex("ZanrDelaNaziv");

                    b.ToTable("MuzickaDela");
                });

            modelBuilder.Entity("muzickeStolice.Model.Ocenljivo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.HasKey("ID");

                    b.ToTable("Ocenljivo");
                });

            modelBuilder.Entity("muzickeStolice.Model.Osoba", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Biografija")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IzvodjacID")
                        .HasColumnType("integer");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("IzvodjacID");

                    b.ToTable("Osobe");
                });

            modelBuilder.Entity("muzickeStolice.Model.Zanr", b =>
                {
                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Naziv");

                    b.ToTable("Zanrovi");
                });

            modelBuilder.Entity("muzickeStolice.Model.Bend", b =>
                {
                    b.HasOne("muzickeStolice.Model.Izvodjac", "Izvodjac")
                        .WithMany()
                        .HasForeignKey("IzvodjacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Izvodjac");
                });

            modelBuilder.Entity("muzickeStolice.Model.Izvodjac", b =>
                {
                    b.HasOne("muzickeStolice.Model.MuzickoDelo", null)
                        .WithMany("Izvodjaci")
                        .HasForeignKey("MuzickoDeloId");
                });

            modelBuilder.Entity("muzickeStolice.Model.MuzickoDelo", b =>
                {
                    b.HasOne("muzickeStolice.Model.Ocenljivo", "Ocenljivo")
                        .WithMany()
                        .HasForeignKey("OcenljivoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("muzickeStolice.Model.Zanr", "ZanrDela")
                        .WithMany()
                        .HasForeignKey("ZanrDelaNaziv");

                    b.Navigation("Ocenljivo");

                    b.Navigation("ZanrDela");
                });

            modelBuilder.Entity("muzickeStolice.Model.Osoba", b =>
                {
                    b.HasOne("muzickeStolice.Model.Izvodjac", "Izvodjac")
                        .WithMany()
                        .HasForeignKey("IzvodjacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Izvodjac");
                });

            modelBuilder.Entity("muzickeStolice.Model.MuzickoDelo", b =>
                {
                    b.Navigation("Izvodjaci");
                });
#pragma warning restore 612, 618
        }
    }
}
